CKPTS:
  datasource: TCGA
  task: "HER2status"  # recurrence or survival
  exp_code: debug

  data_root_dir: "/home/cyyan/Projects/HER2/results/TCGA_2FeatsCCL_20x" # data directory
  # 'csv file with slide_id and label information'
  csv_info_path: "/home/cyyan/Projects/HER2/TCGABRCA_AllSlides_ClinInfo_Status0927.csv"
  # IF not None, manually specify the set of splits to use
  split_dir: "/home/cyyan/Projects/HER2/results/TCGA_3CaseSplits/her2status_KFoldsCV"
  results_dir: "/home/cyyan/Projects/HER2/models" # results directory (default: ./results)
  cfg_to_name: "params_setting.txt"


TRAIN:
  model_type:  ProtoTransformer # ['ProtoTransformer', 'CLAM', 'ProtoMIL', 'ABMIL', 'Transformer'] type of model (default: clam_sb, clam w/ single attention branch)
  encoding_dim:  2048 #'WSI patches encoding dim' [1024, 768, 2048]
  model_size: ccl2048  # ['resnet_small', 'ViT_small', 'ccl2048']' size of model, does not affect mil'

  top_num_inst: # sampling `top_num_inst` instances in model forward according to attention scores, in model 
  top_num_inst_twice: 500
  num_perslide: # None will cover all samples, for data sampling, __getitem__
  n_classes: 2 # 'number of classes (4 bins for survival)'
  label_col: HER2status # label column name, type of survival (OS, DFS, PFI)')
  loss_func: CE # ['ce_surv', 'nll_surv', 'multi_surv'] 'slide-level classification loss function (default: nll_surv)'
  alpha_surv:  0.1 # 'How much to weigh uncensored patients between 0 and 1
  beta_surv:  # beta surv is used only when loss_func is multi_surv; beta val is for ce and 1 - beta is for nll

  log_data: True # log data using tensorboard
  weighted_sample: True # 'enable weighted sampling
  

HyperParams:
  max_epochs: 1000 # 'maximum number of epochs to train (default: 200)'
  batch_size: 1
  gc: 32 # 'Gradient Accumulation Step.'
  lr: 0.0001 # 'learning rate (default: 0.0001)'
  optim: adam  # optimizer, adam sgd adamW radam Lamb
  scheduler: LinearLR # optimizer scheduler [CosineAnnealingLR CyclicLR LinearLR OneCycleLR StepLR]
  drop_out: 0. # fix BUG, should be a float num, enable dropout (p=0.25)'
  early_stopping: True  # enable early stopping

  reg: 0.00001 # 'weight decay (default: 1e-5)'
  lambda_reg: 0.00001 # 'L1-Regularization Strength (Default 1e-5)'


CROSSVALIDATAION:
  times: 1 # number of times (default: 5)
  t_start: -1 # start time (default: -1, last time)
  t_end: -1 # end time (default: -1, first time)
  k: 5 # number of folds (default: 10)
  k_start: -1 # start fold (default: -1, last fold)
  k_end: -1 # end fold (default: -1, first fold)


CLAM_spec:
  no_inst_cluster: True # disable instance-level clustering
  inst_loss: svm # ['svm', 'ce', None] 'instance-level clustering loss function (default: None)'
  subtyping: False # subtyping problem
  bag_weight: 0.7 # 'clam: weight coefficient for bag-level loss (default: 0.7)
  B: 16 # number of positive/negative patches to sample for clam

CLUSTER:
  lib: lib/select_train.ckpt # lib to save wsi id of train set
  preference: 0 # preference for AP clustering
  damping: 0.5 # damping for AP clustering
  prototypes_index: cluster/prototypes_index.ckpt
  global_ap_model: cluster/ap_model.pkl
  feat_dir: # path to save features
  global_cluster_path: "/home/cyyan/Projects/HER2/results/TCGA_3APCluster"
  local_cluster_path: "/home/cyyan/Projects/HER2/results/TCGA_3APCluster/local_files"
  lamb: 0.25



COMMON:
  gpu: "0"
  seed: 2020 # 'random seed for reproducible experiment (default: 2020)'
  workers: 8  # data loader workers
